import { useEffect, useState } from 'react';
import { getReceipt } from '../../lib/api';
import { stroopsToXlm, shortAddress } from '../../lib/stellar';
import type { Receipt } from '../../types';

function printReceipt(receipt: Receipt) {
  const win = window.open('', '_blank', 'width=520,height=680');
  if (!win) return;
  win.document.write(`<!DOCTYPE html><html><head>
    <meta charset="utf-8"/>
    <title>FarmChain Receipt — ${receipt.orderId.slice(0, 8)}</title>
    <style>
      body{font-family:sans-serif;padding:40px;max-width:420px;margin:0 auto;color:#111}
      h1{color:#15803d;font-size:1.25rem;margin-bottom:4px}
      .amount{font-size:2rem;font-weight:700;color:#15803d;text-align:center;margin:16px 0 4px}
      .sub{text-align:center;color:#6b7280;margin-bottom:20px}
      table{width:100%;border-collapse:collapse;font-size:0.85rem}
      td{padding:6px 4px;border-bottom:1px solid #e5e7eb}
      td:first-child{color:#6b7280;width:40%}
      .hash{font-family:monospace;font-size:0.7rem;word-break:break-all}
      .footer{margin-top:24px;font-size:0.75rem;color:#9ca3af;text-align:center}
    </style>
  </head><body>
    <h1>FarmChain Purchase Receipt</h1>
    <div class="amount">${stroopsToXlm(receipt.amount).toFixed(2)} XLM</div>
    <div class="sub">${receipt.quantity} ${receipt.unit ?? ''} of ${receipt.productName ?? 'product'}</div>
    <table>
      <tr><td>Order ID</td><td>${receipt.orderId.slice(0, 8)}…</td></tr>
      <tr><td>Buyer</td><td>${shortAddress(receipt.buyerPk)}</td></tr>
      <tr><td>Farmer</td><td>${shortAddress(receipt.farmerPk)}</td></tr>
      <tr><td>Category</td><td>${receipt.category ?? '—'}</td></tr>
      <tr><td>Date</td><td>${new Date(receipt.createdAt).toLocaleString()}</td></tr>
      ${receipt.txHash ? `<tr><td>Tx Hash</td><td class="hash">${receipt.txHash}</td></tr>` : ''}
    </table>
    <div class="footer">Generated by FarmChain · Powered by Stellar</div>
  </body></html>`);
  win.document.close();
  win.focus();
  win.print();
}

function downloadReceipt(receipt: Receipt) {
  const lines = [
    'FARMCHAIN PURCHASE RECEIPT',
    '==========================',
    `Order ID  : ${receipt.orderId}`,
    `Product   : ${receipt.productName ?? '—'}`,
    `Quantity  : ${receipt.quantity} ${receipt.unit ?? ''}`,
    `Amount    : ${stroopsToXlm(receipt.amount).toFixed(2)} XLM`,
    `Buyer     : ${receipt.buyerPk}`,
    `Farmer    : ${receipt.farmerPk}`,
    `Category  : ${receipt.category ?? '—'}`,
    `Date      : ${new Date(receipt.createdAt).toLocaleString()}`,
    receipt.txHash ? `Tx Hash   : ${receipt.txHash}` : '',
    '',
    'Powered by Stellar · FarmChain',
  ].filter((l) => l !== undefined).join('\n');

  const blob = new Blob([lines], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `farmchain-receipt-${receipt.orderId.slice(0, 8)}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

interface Props {
  orderId: string;
  onClose: () => void;
}

export default function ReceiptModal({ orderId, onClose }: Props) {
  const [receipt, setReceipt] = useState<Receipt | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    getReceipt(orderId)
      .then((res) => {
        const r = res.data.receipt;
        setReceipt({
          id: r.id,
          orderId: r.order_id,
          txHash: r.tx_hash,
          createdAt: r.created_at,
          buyerPk: r.buyer_pk,
          farmerPk: r.farmer_pk,
          amount: Number(r.amount),
          quantity: r.quantity ?? 1,
          productName: r.product_name,
          unit: r.unit,
          category: r.category,
        });
      })
      .catch(() => setError('Could not load receipt.'))
      .finally(() => setLoading(false));
  }, [orderId]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-md p-6 space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-bold text-green-800">Purchase Receipt</h2>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 text-xl leading-none">×</button>
        </div>

        {loading && <p className="text-gray-400 text-sm">Loading…</p>}
        {error && <p className="text-red-500 text-sm">{error}</p>}

        {receipt && (
          <div className="space-y-3 text-sm">
            <div className="bg-green-50 rounded-xl p-4 text-center">
              <p className="text-3xl font-bold text-green-700">
                {stroopsToXlm(receipt.amount).toFixed(2)} XLM
              </p>
              <p className="text-gray-500 mt-1">
                {receipt.quantity} {receipt.unit ?? ''} of {receipt.productName ?? 'product'}
              </p>
            </div>

            <div className="grid grid-cols-2 gap-3 text-sm">
              <div>
                <p className="text-gray-400">Buyer</p>
                <p className="font-mono">{shortAddress(receipt.buyerPk)}</p>
              </div>
              <div>
                <p className="text-gray-400">Farmer</p>
                <p className="font-mono">{shortAddress(receipt.farmerPk)}</p>
              </div>
              <div>
                <p className="text-gray-400">Completed</p>
                <p>{new Date(receipt.createdAt).toLocaleString()}</p>
              </div>
              <div>
                <p className="text-gray-400">Category</p>
                <p className="capitalize">{receipt.category ?? '—'}</p>
              </div>
            </div>

            {receipt.txHash && (
              <div>
                <p className="text-gray-400">Transaction Hash</p>
                <p className="font-mono text-xs break-all text-gray-700">{receipt.txHash}</p>
              </div>
            )}

            <div className="flex gap-2">
              <button
                onClick={() => printReceipt(receipt)}
                className="flex-1 border border-green-600 text-green-700 hover:bg-green-50 py-2 rounded-lg font-medium text-sm transition"
              >
                Print
              </button>
              <button
                onClick={() => downloadReceipt(receipt)}
                className="flex-1 bg-green-700 hover:bg-green-600 text-white py-2 rounded-lg font-medium text-sm transition"
              >
                Download
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
